urls.py
from django.conf.urls import url

from . import views

app_name = 'user_profile'


urlpatterns = [
    url(r'^(?P<slug>[A-Za-z0-9_-]+)$', views.UserProfileDetailView.as_view(), name='userprofile_detail'),
    url(r'^(?P<slug>[A-Za-z0-9_-]+)/update/$', views.UpdateUserProfileView.as_view(), name='userprofile_update'),
]

models.py
from __future__ import unicode_literals

from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

try:
    from django.contrib.auth.backends import get_user_model
    UserModel = get_user_model()

except Exception as e:
    from django.contrib.auth.models import User
    UserModel = User


class ProfileBasicInformation(models.Model):
    class Meta:
        abstract = True

    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField(default=0)
    biography = models.TextField()
    image = models.FileField(blank=True,
                             null=True)


class ProfileContactInformation(models.Model):
    class Meta:
        abstract = True

    telephone = models.CharField(max_length=15,
                                 blank=True,
                                 null=True)
    mobile = PhoneNumberField(
        max_length=15,
        blank=True,
        null=True,
        help_text='eg +254712345678'
    )
    website = models.URLField(blank=True)
    SKYPE = models.CharField(max_length=255,
                             blank=True,
                             null=True,
                             help_text='provide your username')
    FACEBOOK = models.CharField(max_length=255,
                                blank=True,
                                null=True,
                                help_text='provide your username')
    TWITTER = models.CharField(max_length=255,
                               blank=True,
                               null=True,
                               help_text='provide your username')


class ProfileLocationInformation(models.Model):
    class Meta:
        abstract = True

    country = models.CharField(max_length=100,
                               blank=True,
                               null=True)
    city = models.CharField(max_length=100,
                            blank=True,
                            null=True)
    town = models.CharField(max_length=100,
                            blank=True,
                            null=True)
    postal_code = models.CharField(max_length=100,
                                   blank=True,
                                   null=True,
                                   default="Not Provided")


class UserProfile(models.Model):
    user = models.OneToOneField(UserModel)
    slug = models.SlugField(unique=True, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'UserProfile for %s' % self.user.username.capitalize()


class UserProfileBasic(ProfileBasicInformation):
    profile = models.OneToOneField(UserProfile, related_name='userprofile_basic')

    def __str__(self):
        return 'Basic Informaion for %s' % self.profile.user.username


class UserProfileContact(ProfileContactInformation):
    profile = models.OneToOneField(UserProfile, related_name='userprofile_contact')

    def __str__(self):
        return 'Contact Informaion for %s' % self.profile.user.username


class UserProfileLocation(ProfileContactInformation):
    profile = models.OneToOneField(UserProfile, related_name='userprofile_location')

    def __str__(self):
        return 'Location Informaion for %s' % self.profile.user.username

forms.py
from collections import OrderedDict

from django import forms
from .models import UserProfile, UserProfileBasic, UserProfileContact, UserProfileLocation

from betterforms.multiform import MultiModelForm


class UserProfileBasicForm(forms.ModelForm):
    class Meta:
        model = UserProfileBasic
        exclude = ('profile', )

    def __init__(self, *args, **kwargs):
        super(UserProfileBasicForm, self).__init__(*args, **kwargs)

        for field_name, field_obj in self.fields.items():
            if not field_name == 'image':
                field_obj.widget.attrs.update({'class': 'form-control'})


class UserProfileContactForm(forms.ModelForm):
    class Meta:
        model = UserProfileContact
        exclude = ('profile', )

    def __init__(self, *args, **kwargs):
        super(UserProfileContactForm, self).__init__(*args, **kwargs)

        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs.update({'class': 'form-control'})


class UserProfileLocationForm(forms.ModelForm):
    class Meta:
        model = UserProfileLocation
        exclude = ('profile', )

    def __init__(self, *args, **kwargs):
        super(UserProfileLocationForm, self).__init__(*args, **kwargs)

        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs.update({'class': 'form-control'})


class UserProfileForm(MultiModelForm):
    form_classes = OrderedDict((
        ('basic', UserProfileBasicForm),
        ('contact', UserProfileContactForm),
        ('location', UserProfileLocationForm),
    ))

views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, UpdateView, TemplateView
from .forms import UserProfileForm
from .models import UserProfile
from permissions import ProfileOwnerMixin

from braces.views import LoginRequiredMixin


class UserProfileDetailView(LoginRequiredMixin, ProfileOwnerMixin, DetailView):
    model = UserProfile
    template_name = 'user_profile/userprofile_detail.html'


class UpdateUserProfileView(LoginRequiredMixin, ProfileOwnerMixin, UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'user_profile/userprofile_update.html'

    def form_valid(self, form):
        return super(UpdateUserProfileView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(UpdateUserProfileView, self).get_form_kwargs()
        kwargs.update(
            instance={
                'userprofile': self.object,
                'basic': self.object.userprofile_basic,
                'contact': self.object.userprofile_contact,
                'location': self.object.userprofile_location,
            }
        )
        return kwargs

    def get_success_url(self):
        messages.success(self.request, 'Profile Successfully Updated')
        return reverse('user_profile:userprofile_detail', kwargs={'slug': self.request.user, })

templates/base.html
{% load static %}
{% load dependancies %}
{% load navigation_links %}
{% check_requirements %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="{% static 'user_profile/css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'user_profile/css/profile.css' %}" rel="stylesheet" type="text/css">

    <title>
        {% block title %}
            {{ title }}
        {% endblock title %}
    | Profile
    </title>
</head>
<body>

<ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="{% url 'user_profile:userprofile_index' %}">Home</a></li>

    {% if  request.user.is_authenticated %}
        {% profile_link %}
        <li role="presentation"><a href="{% url 'account_logout' %}">Logout</a></li>

    {% else %}
        <li role="presentation"><a href="{% url 'account_login' %}">Login</a></li>
    {% endif %}
</ul>

{% include 'user_profile/tags/messages.html' %}

{% block content %}

{% endblock content %}

 <!-- JS -->
<script src="{% static 'js/jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/user_profile/tags/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <ul class="messages list-unstyled">
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    <strong>{{ message.tags|capfirst }}.</strong> {{ message }}.
                </li>
            </ul>
        </div>
    {% endfor %}
{% endif %}

templates/user_profile/tags/nav/profile_link.html
<li role="presentation"><a href="{{ link }}">View my Profile <span class="fa fa-user"></span></a></li>

templates/user_profile/tags/nav/update_link.html
<a class="userprofile-edit pull-right" href="{{ link }}">Update Profile <span class="fa fa-pencil"></span> </a>

templates/user_profile/tags/userprofile_detail_snippets/basic.html
{% load navigation_links %}

<div id="basic" class="tab-pane in active">
	<div class="row">
		<div class="col-xs-12 col-sm-3 center">
			<span class="profile-picture">
				<img class="editable img-responsive" alt=" {{ request.user|capfirst }}" id="avatar2" src="{% if userprofile.userprofile_basic.image %}{{ userprofile.userprofile_basic.image.url }}{% else %}{% endif %}">
			</span>

			<div class="space space-4"></div>

		</div><!-- /.col -->

		<div class="col-xs-12 col-sm-9">
			<h4 class="blue">
				<span class="middle">{% update_link %}</span>

				<span class="label label-purple arrow-circle-o-right">
					<i class="ace-icon fa fa-circle smaller-80 align-middle"></i>
					online
				</span>
			</h4>

			<div class="profile-user-info">
				<div class="profile-info-row">
					<div class="profile-info-name"> Username </div>

					<div class="profile-info-value">
						<span>{{ request.user|capfirst }}</span>
					</div>
				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> First Name </div>

					<div class="profile-info-value">
						<span>{{ userprofile.userprofile_basic.first_name }}</span>
					</div>
				</div>

                <div class="profile-info-row">
					<div class="profile-info-name"> Middle Name </div>

					<div class="profile-info-value">
						<span>{{ userprofile.userprofile_basic.middle_name }}</span>
					</div>
				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> Last Name </div>

					<div class="profile-info-value">
						<span>{{ userprofile.userprofile_basic.last_name }}</span>
					</div>
				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> Age </div>

					<div class="profile-info-value">
						<span>{{ userprofile.userprofile_basic.age }}</span>
					</div>

				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> Joined </div>

					<div class="profile-info-value">
						<span>{{ request.user.date_joined }}</span>
					</div>
				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> Last Login </div>

					<div class="profile-info-value">
						<span>{{ request.user.last_login|timesince }} ago</span>
					</div>
				</div>
			</div>

			<div class="hr hr-8 dotted"></div>

		</div><!-- /.col -->
	</div><!-- /.row -->

	<div class="space-20"></div>

	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<div class="widget-box transparent">
				<div class="widget-header widget-header-small">
					<h4 class="widget-title smaller">
						<i class="ace-icon fa fa-check-square-o bigger-110"></i>
						Little About Me
					</h4>
				</div>

				<div class="widget-body">
					<div class="widget-main">
						<p>
							{{ userprofile.userprofile_basic.biography }}
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- /#basic -->

templates/user_profile/tags/userprofile_detail_snippets/contact.html
<div id="contact" class="tab-pane">
	<div class="profile-contact row">

		<div class="col-sm-6">
			<div class="profile-info-row">
				<div class="profile-info-name"> Mobile </div>

				<div class="profile-info-value">
					<span>{{ userprofile.userprofile_contact.mobile }}</span>
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name"> Telephone </div>

				<div class="profile-info-value">
					<span>{{ userprofile.userprofilebasic.telephone }}</span>
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name">
					<i class="middle ace-icon fa fa-internet-explorer bigger-150 blue"></i>
				</div>

				<div class="profile-info-value">
					{% if userprofile.userprofile_contact.website %}
					<a href="{{ userprofile.userprofile_contact.website }}" target="_blank">{{ userprofile.userprofile_contact.website }}</a>
					{% else %}
					Not Provided
					{% endif %}
				</div>

			</div>

			<div class="profile-info-row">
				<div class="profile-info-name">
					<i class="middle ace-icon fa fa-skype bigger-150 blue"></i>
				</div>

				<div class="profile-info-value">
					{% if userprofile.userprofile_contact.SKYPE %}
					<a href="https://skype.com/{{ userprofile.userprofile_contact.SKYPE }}">Skype me </a>
					{% else %}
					Not Provided
					{% endif %}
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name">
					<i class="middle ace-icon fa fa-facebook-square bigger-150 blue"></i>
				</div>

				<div class="profile-info-value">
					{% if userprofile.userprofile_contact.FACEBOOK %}
					<a href="https://facebook.com/{{ userprofile.userprofile_contact.FACEBOOK }}">Find me on Facebook </a>
					{% else %}
					Not Provided
					{% endif %}
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name">
					<i class="middle ace-icon fa fa-twitter-square bigger-150 blue"></i>
				</div>

				<div class="profile-info-value">
					{% if userprofile.userprofile_contact.TWITTER %}
					<a href="https://twitter.com/{{ userprofile.userprofile_contact.TWITTER }}">Follow me on Twitter </a>
					{% else %}
					Not Provided
					{% endif %}
				</div>

			</div>
		</div>
		<!-- /.col -->
	</div><!-- /.row -->
	<div class="space-12"></div>
</div><!-- /#contact -->

templates/user_profile/tags/userprofile_detail_snippets/location.html
<div id="location" class="tab-pane">
	<div class="profile-contact row">

		<div class="col-sm-6">
			<div class="profile-info-row">
				<div class="profile-info-name"> Country </div>

				<div class="profile-info-value">
					<span>
                        {% if userprofile.userprofile_location.country %}
                            {{ userprofile.userprofile_location.country }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </span>
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name"> City </div>

				<div class="profile-info-value">
					<span>
                        {% if userprofile.userprofile_location.city %}
                            {{ userprofile.userprofile_location.city }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </span>
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name"> Town </div>

				<div class="profile-info-value">
					<span>
                        {% if userprofile.userprofile_location.town %}
                            {{ userprofile.userprofile_location.town }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </span>
				</div>

			</div>
			<div class="profile-info-row">
				<div class="profile-info-name"> Postal Code </div>

				<div class="profile-info-value">
					<span>
                        {% if userprofile.userprofile_location.postal_code %}
                            {{ userprofile.userprofile_location.postal_code }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </span>
				</div>

			</div>

		</div>
		<!-- /.col -->
	</div><!-- /.row -->
	<div class="space-12"></div>
</div><!-- /#location -->

templates/user_profile/tags/userprofile_detail_snippets/tabs.html
<ul class="nav nav-tabs padding-18">
	<li class="active">
		<a data-toggle="tab" href="#basic">
			<i class="green ace-icon fa fa-user bigger-120"></i>
			Profile
		</a>
	</li>

	<li>
		<a data-toggle="tab" href="#contact">
			<i class="orange ace-icon fa fa-phone bigger-120"></i>
			Contact
		</a>
	</li>

	<li>
		<a data-toggle="tab" href="#location">
			<i class="orange ace-icon fa fa-map bigger-120"></i>
			Location
		</a>
	</li>
</ul>

templates/user_profile/userprofile_create.html
{% extends 'base.html' %}
{% block title %}
    form
{% endblock title %}

{% block content %}
    <div class="container-fluid">
        {% include 'user_profile/tags/messages.html' %}
        <form method="post" action="">
            {% csrf_token %}
            <div class="form-group">
                <h3>Basic Information</h3>
            </div>
            {{ form.basic }}
            <div class="form-group">
                <br/>
                <input type="submit" class="btn btn-primary btn-block" value="Update Profile">
            </div>
        </form>
    </div>
{% endblock content %}

templates/user_profile/userprofile_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ object.user|capfirst }}
{% endblock title %}

{% block content %}
    <div class="container">

        <h1 class="page-header text-center">Profile Information for {{ request.user|upper }}</h1>

        <div class="userprofile">

            <div id="user-profile-2" class="user-profile">

                <div class="tabbable">

                    {% include 'user_profile/tags/userprofile_detail_snippets/tabs.html' %}

                    <div class="tab-content no-border padding-24">

                        {% include 'user_profile/tags/userprofile_detail_snippets/basic.html' %}

                        {% include 'user_profile/tags/userprofile_detail_snippets/contact.html' %}

                        {% include 'user_profile/tags/userprofile_detail_snippets/location.html' %}

                    </div>

                </div>

            </div>

        </div>

    </div>

{% endblock content %}

templates/user_profile/userprofile_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}
form
{% endblock title %}

{% block content %}
<div class="container-fluid">
	<div class="col-lg-6 col-lg-offset-3">

		<form method="post" action="{% url 'user_profile:userprofile_update' request.user %}" enctype="multipart/form-data">
			{% csrf_token %}

			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="basicHeading">
						<h4 class="panel-title text-center">
							<a class="" role="button" data-toggle="collapse" data-parent="#accordion" href="#basic" aria-expanded="true" aria-controls="collapseOne">
                                 Basic Information(click me)
							</a>
						</h4>
					</div>
					<div id="basic" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="basicHeading">
						<div class="panel-body">
							<div class="userprofile">
								<div class="form-group">
									<h3 class="page-header text-center"></h3>
								</div>
								{{ form.basic|crispy }}
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="basicHeading">
						<h4 class="panel-title text-center">
							<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#contact" aria-expanded="false" aria-controls="contact">
								Contact Information(click me)
							</a>
						</h4>
					</div>
					<div id="contact" class="panel-collapse collapse" role="tabpanel" aria-labelledby="contactHeading">
						<div class="panel-body">
							<div class="userprofile">
								<div class="form-group">
									<h3 class="page-header text-center"></h3>
								</div>
								{{ form.contact|crispy }}
							</div>

						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="locationHeading">
						<h4 class="panel-title text-center">
							<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#location" aria-expanded="false" aria-controls="location">
								Location Information(click me)
							</a>
						</h4>
					</div>
					<div id="location" class="panel-collapse collapse" role="tabpanel" aria-labelledby="locationHeading">
						<div class="panel-body">

							<div class="userprofile">
								<div class="form-group">
									<h3 class="page-header text-center"></h3>
								</div>
								{{ form.location|crispy }}
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="form-group">
				<br/>
				<input type="submit" class="btn btn-primary btn-block" value="Update Profile">
			</div>
		</form>
	</div>
</div>
{% endblock content %}